--交易头表
CREATE TABLE tranhead (
  id int not null AUTO_INCREMENT,
  storeId varchar(8) NOT NULL , -- '店号'
  posNo int NOT NULL , -- '收款机台号'
  transactionNumber int NOT NULL , -- '交易序号'
  dealType1 char(1) NOT NULL , -- '交易明细类别(''0一般交易,*作废交易,表示本笔为被作废交易,1交易未完成)'
  dealType2 char(1) NOT NULL , -- '交易类别(0销售交易,3退货,4PaidIn/PaidOut交易,5挂单,8开班,9交班,B上班打卡作业,C下班打卡作业,D日结,G投库,H借零,Q报废)'
  dealType3 char(1) NOT NULL , -- '交易明细类别(0正常,1作废,表示本笔作废交易,2重印作废,表示本笔重印作废交易,交易取消作废,4退货交易)'
  accountDate date NOT NULL , -- '营业日期'
  shiftNumber int NOT NULL , -- '班别号'
  zNumber int NOT NULL , -- '日结号'
  systemDate datetime NOT NULL DEFAULT '1970-01-01 00:00:00', -- '交易时间'
  cashierNo varchar(20) NOT NULL , -- '收银员编号'
  detailCount int NOT NULL , -- '明细项数'
  saleAmount decimal(12,2) NOT NULL , -- '小计金额'
  payNo1 varchar(2) DEFAULT '' , -- '支付代号1'
  payAmount1 decimal(12,2) DEFAULT NULL , -- '支付金额1'
  payNo2 varchar(2) DEFAULT '' , -- '支付代号2'
  payAmount2 decimal(12,2) DEFAULT NULL , -- '支付金额2'
  payNo3 varchar(2) DEFAULT '' , -- '支付代号3'
  payAmount3 decimal(12,2) DEFAULT NULL , -- '支付金额3'
  payNo4 varchar(2) DEFAULT '' , -- '支付代号4'
  payAmount4 decimal(12,2) DEFAULT NULL , -- '支付金额4'
  taxAmount decimal(12,2) DEFAULT 0.00 , -- '税金'
  changeAmount decimal(12,2) DEFAULT 0.00 , -- '找零'
  overAmount decimal(12,2) DEFAULT NULL,
  roundDownAmount decimal(12,2) DEFAULT 0.00 , -- '舍零去分'
  memberId varchar(50) DEFAULT '' , -- '会员编号'
  grossSaleAmount decimal(12,2) DEFAULT 0.00 , -- '营业毛额'
  netSaleTotalAmount decimal(12,2) DEFAULT 0.00 , -- '销售合计'
  mmDiscountAmount decimal(12,2) DEFAULT 0.00 , -- '促销金额合计'
  daishouAmount decimal(12,2) DEFAULT 0.00 , -- '代售合计'
  daishou2Amount decimal(12,2) DEFAULT 0.00 , -- '代收合计'
  daifuAmount decimal(12,2) DEFAULT 0.00 , -- '代付合计'
  customerId varchar(1),--'客层'
  customerCount int,--'来客数'
  voidTransactionNumber int,--'退货原交易号'
  voidPosNo int, --'退货原机号'
  isMemberOffLine char(1), --'是否离线会员  Y是,N否'
  platDiscount decimal(12,2), --'资金方优惠金额'
  uploadFlag varchar(1) not null, --'上传旗标 0未上传 1已上传'

  PRIMARY KEY (id,storeId,posNo,transactionNumber)
);
