-- 交易明细表
CREATE TABLE trandetail (
  id int not null AUTO_INCREMENT, -- 'id自增长'
  storeId varchar(8) NOT NULL , -- '店号'
  posNo int NOT NULL , -- '收款机台号'
  transactionNumber int NOT NULL , -- '交易序号'
  itemSeq int NOT NULL , -- '明细序号'
  systemDate datetime NOT NULL DEFAULT '1970-01-01 00:00:00', -- '交易时间'
  detailCode varchar(1) , -- '交易明细代码("S":销售,"R":退货,"D":SI折扣,"M":Mix & Match折扣,"I":代售,"O":代收公共事业费,"Q":代付,"V":指定更正,"E":立即更正,‘G’:投库,‘H’:借零,"N":PaidIn,"T":PaidOut,"A":舍零去分'
  itemVoid varchar(1) DEFAULT '' , -- '是否更正(0正常销售,1已更正)'
  catNo varchar(4) DEFAULT '' , -- '大分类编号'
  midCatNo varchar(6) DEFAULT '' , -- '中分类编号'
  microCatNo varchar(6) DEFAULT '' , -- '小分类编号'
  pluNo varchar(8) DEFAULT '' , -- '系统货号'
  itemNumber varchar(13) DEFAULT '' , -- '条码'
  pluName varchar(50) DEFAULT '' , -- '商品名称'
  origPrice decimal(12,2) DEFAULT 0.00 , -- '原售价'
  unitPrice decimal(12,2) DEFAULT 0.00 , -- '单价'
  qty decimal(12,2) DEFAULT 0.00 , -- '数量'
  amount decimal(12,2) DEFAULT 0.00 , -- '金额'
  afterAmount decimal(12,2) DEFAULT 0.00 , -- '分摊折扣后金额'
  taxType varchar(2) DEFAULT '' , -- '税别代号'
  taxAmount decimal(12,2) DEFAULT 0.00 , -- '税金'
  discountNo varchar(52) DEFAULT '' , -- '折扣代号或代收条码'
  memo varchar(255) DEFAULT '' , -- '备注'
  mmType varchar(2), -- '促销类型'
  mmType2 varchar(2), -- '促销类型 SC用'
  mmBeforeAmtount decimal(12,2), -- '促销前金额'
  mmAmount decimal(12,2), -- '促销金额'
  mmAfterAmount decimal(12,2), -- '促销后金额'
  inv int, -- '是否负库存销售'
  mmType3 varchar(3), -- '促销类型 SC用'
  uploadFlag varchar(1) not null DEFAULT '0',
  PRIMARY KEY (id,storeId,posNo,transactionNumber,itemSeq)
);