/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_knowledge_android_jnistudy_JniTest */

#ifndef _Included_com_example_knowledge_android_jnistudy_JniTest
#define _Included_com_example_knowledge_android_jnistudy_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_knowledge_android_jnistudy_JniTest
 * Method:    getString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_knowledge_1android_jnistudy_JniTest_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
